# Generated by Django 4.1.5 on 2023-05-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apt_no', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agent', to='user.agent')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Landlord', to='user.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_update', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountReference', models.CharField(max_length=50)),
                ('paidAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paymentDate', models.DateField()),
                ('transactionId', models.CharField(max_length=150)),
                ('phoneNumber', models.IntegerField()),
                ('fullName', models.CharField(max_length=150)),
                ('invoiceName', models.CharField(max_length=150)),
                ('externalReference', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landlord', models.CharField(max_length=150)),
                ('No_Apartments', models.CharField(max_length=150)),
                ('Units_count', models.CharField(max_length=150)),
                ('Tenants_count', models.CharField(max_length=150)),
                ('Expected_Amount', models.CharField(max_length=150)),
                ('Paid_Tenants', models.CharField(max_length=150)),
                ('Paid_Amount', models.CharField(max_length=150)),
                ('Deficit_Amount', models.CharField(max_length=150)),
                ('Not_Paid_Tenants', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('door_no', models.CharField(max_length=50)),
                ('rent', models.IntegerField()),
                ('Rent_status', models.CharField(choices=[('Paid', 'Paid'), ('In Arrears', 'In Arrears'), ('confirm', 'confirm'), ('unavailable', 'unavailable')], default='unavailable', max_length=50)),
                ('hse_status', models.CharField(choices=[('occupied', 'occupied'), ('Empty', 'Empty')], default='Empty', max_length=50)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='dashboard.apartment')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tenant')),
            ],
            options={
                'unique_together': {('door_no', 'apartment')},
            },
        ),
    ]
