# Generated by Django 4.1.5 on 2023-05-25 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agt_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=50)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=50)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.agent')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('te_id', models.IntegerField(unique=True)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Landlords', to='user.landlord')),
            ],
        ),
    ]
